### ISSUE TITLE
Make model configurable? 

### ISSUE THREAD

**Issue by sebastian-philipp** [JohannesBuchner/thunderbird-ai-grammar-mailextension#1]
People might want to try out different (smaller or bigger? models)

**Comment by JohannesBuchner** [comment]
I think for this you would have to download the folder, see 
https://github.com/JohannesBuchner/thunderbird-ai-grammar-mailextension?tab=readme-ov-file#making-changes
for the "Manual installation" steps.

Then you have to edit line 62 in popup.js to a different model, and then load the extension (see steps) into thunderbird.

**Comment by JohannesBuchner** [comment]
I am closing this for now. If you have a specific better model that you are using frequently, and think that would be useful to a large number of people, please reopen. In the meanwhile, I think choosing a good prompt may need more work.
