### ISSUE TITLE
HTML mails

### ISSUE THREAD

**Issue by sebastian-philipp** [JohannesBuchner/thunderbird-ai-grammar-mailextension#2]
Seems as the "Grammar" button doesn't do anything: 

![image](https://github.com/JohannesBuchner/thunderbird-ai-grammar-mailextension/assets/2574405/70330383-16f6-491a-842e-8f099390c6d9)

I don't see anything in the developer console. No error message, not http request. The only request I see comes from the settings page "Test" button with appears to be working.

Thunderbird 115.10.1 (64-Bit)

**Edit: reason was it only works for plain-text mails.**

**Comment by JohannesBuchner** [comment]
That is very strange.

**Comment by JohannesBuchner** [comment]
Ah I see.

This extensions only works on text emails, not HTML emails. This is mentioned in the addon description.

**Comment by JohannesBuchner** [comment]
Here is how to switch: https://superuser.com/questions/1639802/in-thunderbird-while-composing-an-email-how-to-convert-it-from-plain-text-to-h

**Comment by sebastian-philipp** [comment]
yes, that works better. Than let me change this to a feature request for HTML emails.

**Comment by JohannesBuchner** [comment]
Maybe you can try out the code in the feature-html branch
https://github.com/JohannesBuchner/thunderbird-ai-grammar-mailextension/compare/main...feature-html

Overriding the HTML with fresh text is quite easy, see this line of code:  https://github.com/JohannesBuchner/thunderbird-ai-grammar-mailextension/compare/main...feature-html#diff-3df6958c77d615b266b54fcf12fadf313e7c1e4b168f0c61ea8c3424eb39eb8cR166

But ideally we would rip out the existing `<p>` at the start, replace them with `<p>` lines from the plain text, but leave everything after (signature, quoted text) intact.
https://github.com/JohannesBuchner/thunderbird-ai-grammar-mailextension/compare/main...feature-html#diff-3df6958c77d615b266b54fcf12fadf313e7c1e4b168f0c61ea8c3424eb39eb8cR171
That's what the insertParagraphs function is intended to do, but I think it is not right. Maybe you can test it with console.log debugging and edit it to suit your needs.

Instructions for how to load the modified extension are at:
https://github.com/JohannesBuchner/thunderbird-ai-grammar-mailextension?tab=readme-ov-file#making-changes
video: https://github.com/JohannesBuchner/thunderbird-ai-grammar-mailextension/raw/main/doc/debug-install.webm

**Comment by JohannesBuchner** [comment]
A zip of the feature-html branch can be downloaded via: https://github.com/JohannesBuchner/thunderbird-ai-grammar-mailextension/archive/refs/heads/feature-html.zip

**Comment by chisel900** [comment]
Thanks for the info on this add-on. I have the html version installed and it works. I guess there is quite a challenge to make this version work with html emails. Currently it works but the corrected text converts the email back to plain text. I guess this is to be expected?

**Comment by JohannesBuchner** [comment]
Yeah. Unfortunately HTML emails can be almost anything. Supporting this is a nightmare that I do not want to get into. 

Also you should be a little worried about letting a LLM generate arbitrary HTML code that you will send to other people...

**Comment by JohannesBuchner** [comment]
I uploaded version 2, which has a bit of support for HTML emails, please test it.

**Comment by geomorillo** [comment]
404 not found when Button Test clicked under Options
here is the server.log [GIN] 2024/08/05 - 13:49:07 | 404 |       184.6µs |       127.0.0.1 | POST     "/api/generate"
Note: Ollama is running, im on w10

**Comment by geomorillo** [comment]
> 404 not found when Button Test clicked under Options here is the server.log [GIN] 2024/08/05 - 13:49:07 | 404 | 184.6µs | 127.0.0.1 | POST "/api/generate" Note: Ollama is running, im on w10


        var data = JSON.stringify({
           "model": "llama3", //i dont have it installed
           "prompt": "Respond with 'it is working!'.",
          "stream": false
        });
After debuggin the extension i realized i dont have the model llama3 installed, so either i install it or maybe you can provide an option to select or change the model name so i will install it first thanks, it should work after installing it

**Comment by JohannesBuchner** [comment]
Thanks for the report. Next time, please open a new issue for a new bug. I'll close this one, since there is primitive support for HTML emails now, and someone else can refine it in a new issue if they are motivated.
