### ISSUE TITLE
grammar correction on reply emails

### ISSUE THREAD

**Issue by jgato** [JohannesBuchner/thunderbird-ai-grammar-mailextension#5]
is there any way that, when replying, to only propose correction on the replied text only?

**Comment by JohannesBuchner** [comment]
Are you asking for html emails or text emails? I think this works for text emails if you have double newlines.

For html emails, you would have to help implement some logic here: 
https://github.com/JohannesBuchner/thunderbird-ai-grammar-mailextension/blob/main/popup.js#L126
which detects the reply chunks.

**Comment by jgato** [comment]
you are right.. I was using html emails :)
